# Generated by Django 3.0.14 on 2024-08-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='name',
        ),
    ]
